"""
embedded_test_cases.py — v0.3.0+

各 domain test cases 的「絕對 fallback」副本。

# 為什麼存在?
- DB 連線失敗 / migration 未跑時,test_runner 仍能讀到 cases
- v0.3.0 migration 003 的種子(從這裡推 26 個 tflex cases 進 DB)
- 之後若使用者刪庫,從這裡可以還原

# 規範
- 每個 case 是 dict,結構對齊 TestCaseRepository schema
- key 是 domain 名稱,value 是 list[case_dict]
- case_id 在同 domain 內 unique

# 注意:此檔內容是 v0.3.0 launch 的 baseline。
# v0.3.0 之後,使用者透過 UI 編輯的 cases 在 MongoDB 內,
# embedded 副本不會自動同步。
"""

from __future__ import annotations


EMBEDDED_TEST_CASES: dict[str, list[dict]] = {
    "tflex": [
        {
            'case_id': '01',
            'name': '各公司退單率與申請數(雙軸 bar+line)',
            'query': '比較各公司的退單率與申請數,我想同時看到絕對量與比率',
            'type': 'happy_path',
            'expected_chart': '雙軸 bar+line',
            'expected_q_cols_any': ['company_code'],
            'expected_q_cols_all': ['average_return_rate'],
            'echarts_min_series': 2,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': '02',
            'name': 'TST vs TSK 員工送單率(小樣本陷阱)',
            'query': '比較 TST 與 TSK 兩家公司的員工送單率',
            'type': 'happy_path',
            'expected_chart': 'percentage bar',
            'expected_q_cols_all': ['company_code'],
            'echarts_min_series': 1,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': '03',
            'name': 'PAY vs RTN(stacked bar)',
            'query': '畫出各公司的 PAY 與 RTN 申請數量,我想看哪家公司退件量最大',
            'type': 'happy_path',
            'expected_chart': 'stacked bar',
            'expected_q_cols_all': ['pay_count', 'return_count', 'company_code'],
            'echarts_min_series': 2,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
        },
        {
            'case_id': '04',
            'name': '各公司 AI 審查率(vs 43% 目標)',
            'query': '哪些公司的 AI 審查率比較高?跟 43% 的目標比起來如何?',
            'type': 'happy_path',
            'expected_chart': 'percentage bar',
            'expected_q_cols_all': ['company_code'],
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': '05',
            'name': 'AI vs Human review by 公司(grouped 不堆疊)',
            'query': '看一下每家公司在 AI 審查跟人工審查的件數分佈,我想找出還是高度依賴人工的公司',
            'type': 'happy_path',
            'expected_chart': 'grouped bar',
            'expected_q_cols_all': ['company_code'],
            'echarts_min_series': 2,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': '06',
            'name': '各公司審核完成率排序',
            'query': '排序各公司的審核完成率,看誰積壓最嚴重',
            'type': 'happy_path',
            'expected_chart': 'sorted single rate bar',
            'expected_q_cols_all': ['company_code'],
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': '07',
            'name': '申請類別分布(非公司維度)',
            'query': '四個福利申請類別,哪個最熱門?',
            'type': 'happy_path',
            'expected_chart': 'categorical bar',
            'expected_q_cols_all': ['application_category'],
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': '08',
            'name': '公司 × 類別 熱力圖(壓力測試)',
            'query': '畫一張熱力圖,看不同公司在四個申請類別的分佈差異',
            'type': 'happy_path',
            'expected_chart': 'heatmap',
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_visualmap': True,
        },
        {
            'case_id': '09',
            'name': 'AI 審查率 vs 退單率散點圖',
            'query': 'AI 審查率跟退單率有相關嗎?畫個散點圖看看',
            'type': 'happy_path',
            'expected_chart': 'scatter',
            'expected_q_cols_all': ['company_code'],
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': '10',
            'name': 'TOP 5 退件公司(陷阱:DB 不可 $sort/$limit)',
            'query': '列出退件數量最多的前 5 名公司,搭配柱狀圖',
            'type': 'happy_path',
            'expected_chart': 'sorted bar',
            'expected_q_cols_all': ['company_code', 'return_count'],
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'phase_a_forbidden_strict': True,
            'phase_b_top_n': 5,
        },
        {
            'case_id': '11',
            'name': '全公司完整 KPI 一覽表(table fallback)',
            'query': '幫我整理一張完整的公司 KPI 表格:申請數、完成數、PAY、RTN、退單率、AI 率、員工送單率全都要',
            'type': 'happy_path',
            'expected_chart': 'table or wide visualization',
            'expected_q_cols_all': ['company_code'],
            'expected_q_min_columns': 5,
        },
        {
            'case_id': 'T1',
            'name': '公司 KPI 執行摘要 (精美表格 + KPI 卡片)',
            'query': '幫我做一份完整的公司 KPI 執行摘要 dashboard:申請數、完成率、退單率、AI 採用率都要,並在最上方放總體 KPI 卡片',
            'type': 'happy_path',
            'expected_chart': 'table with KPI cards',
            'expected_q_cols_all': ['company_code'],
            'echarts_min_kpi_cards': 3,
            'echarts_should_have_kpi_cards': True,
            'echarts_should_use_table': True,
        },
        {
            'case_id': 'T2',
            'name': '退單率異常排行表(條件格式)',
            'query': '找出退單率最高的公司排行表,並標註哪些公司明顯高於整體平均',
            'type': 'happy_path',
            'expected_chart': 'sorted table or bar',
            'expected_q_cols_all': ['company_code'],
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
        },
        {
            'case_id': 'T3',
            'name': '申請量 TOP 5 vs BOTTOM 5 對比',
            'query': '申請量最大跟最少的各 5 家公司,做一張對比表呈現',
            'type': 'happy_path',
            'expected_chart': 'comparison table',
            'expected_q_cols_all': ['company_code'],
        },
        {
            'case_id': '12',
            'name': '過去三個月趨勢(拒絕:無 date)',
            'query': '我想看過去三個月每週的申請趨勢',
            'type': 'refusal',
            'refusal_keywords': ['資料不足', '無 date', 'no application date', 'no date', 'missing', '不支援', '缺少', '不存在', '無法分析', '沒有', '限制', '趨勢'],
        },
        {
            'case_id': '13',
            'name': '各部門退單率(拒絕:無 department)',
            'query': '各部門的退單率比較,哪個部門最高?',
            'type': 'refusal',
            'refusal_keywords': ['資料不足', '無', '缺', '不支援', 'department', '部門', 'missing', '限制', '不存在'],
        },
        {
            'case_id': '14',
            'name': '平均申請金額(拒絕:無 amount)',
            'query': '員工每次申請的平均金額是多少?哪家公司平均最高?',
            'type': 'refusal',
            'refusal_keywords': ['資料不足', '無', '缺', '不支援', 'amount', '金額', 'missing', '限制', '不存在'],
        },
        {
            'case_id': '15',
            'name': '平均審核時間(拒絕:無 timestamp)',
            'query': '平均審核需要幾天?AI 跟人工誰比較快?',
            'type': 'refusal',
            'refusal_keywords': ['資料不足', '無', '缺', '不支援', 'timestamp', '時間', 'missing', '限制', '不存在', '無法'],
        },
        {
            'case_id': 'STK-01',
            'name': '100% stacked bar:per company × category',
            'query': '畫一張 stacked bar:依據 company_code(TST、TSN、TSC),每條 bar 中呈現 application_category 的佔比',
            'type': 'happy_path',
            'expected_chart': '100% stacked bar',
            'expected_q_cols_any': ['company_code', 'application_category'],
            'echarts_data_length_aligned': True,
            'echarts_min_series': 2,
            'echarts_no_placeholder_series_name': True,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_series_count_max': 6,
            'echarts_should_have_stack': True,
            'echarts_xaxis_unique': True,
            'echarts_yaxis_max': 100,
        },
        {
            'case_id': 'STK-02',
            'name': '100% stacked transposed:per category × company',
            'query': '依據 application_category 畫 stacked bar,每條 bar 中呈現 TST、TSN、TSC 的占比',
            'type': 'happy_path',
            'expected_chart': 'transposed 100% stacked bar',
            'expected_q_cols_any': ['company_code', 'application_category'],
            'echarts_data_length_aligned': True,
            'echarts_min_series': 2,
            'echarts_no_placeholder_series_name': True,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
            'echarts_xaxis_unique': True,
            'echarts_yaxis_max': 100,
        },
        {
            'case_id': 'STK-03',
            'name': 'Raw count stacked:PAY vs RTN by company',
            'query': '各公司的 PAY 與 RTN 申請數量比較,用 stacked bar 呈現',
            'type': 'happy_path',
            'expected_chart': 'stacked bar (raw count)',
            'expected_q_cols_all': ['company_code'],
            'echarts_data_length_aligned': True,
            'echarts_min_series': 2,
            'echarts_no_placeholder_series_name': True,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
            'echarts_xaxis_unique': True,
        },
        {
            'case_id': 'STK-04',
            'name': '三狀態 100% stacked:per category × (approved/returned/in_progress)',
            'query': '各申請類別下,核准(完成且 result=Y)/退件(完成且 result=N)/進行中三狀態的占比分佈,用 100% stacked bar',
            'type': 'happy_path',
            'expected_chart': '3-state 100% stacked',
            'expected_q_cols_any': ['application_category'],
            'echarts_data_length_aligned': True,
            'echarts_min_series': 3,
            'echarts_no_placeholder_series_name': True,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
            'echarts_xaxis_unique': True,
            'echarts_yaxis_max': 100,
        },
        {
            'case_id': 'STK-05',
            'name': 'Stacked + filter:TST/TSC 各類別 AI vs Human',
            'query': '只看 TST、TSC 兩家,各類別中 AI 審查 vs 人工審查 的數量 stacked',
            'type': 'happy_path',
            'expected_chart': 'stacked bar with filter',
            'expected_q_cols_any': ['application_category'],
            'echarts_data_length_aligned': True,
            'echarts_min_series': 2,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
            'echarts_xaxis_unique': True,
            'phase_a_must_have_match_in': True,
        },
        {
            'case_id': 'STK-06',
            'name': 'Edge:hc 範圍過濾 + 缺漏組合',
            'query': '依據 hc 介於 100 到 1000 的公司,看 application_category 占比 stacked',
            'type': 'happy_path',
            'expected_chart': 'stacked bar with hc filter',
            'echarts_data_length_aligned': True,
            'echarts_min_series': 2,
            'echarts_no_nan_in_data': True,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
            'echarts_xaxis_unique': True,
        },
        {
            'case_id': 'STK-07',
            'name': 'Follow-up:基本 bar 改 stacked (需 last_analysis)',
            'query': '改成 stacked bar 看類別占比',
            'type': 'happy_path',
            'expected_chart': 'follow-up stacked',
            'follow_up_setup_query': '各公司的申請數量 bar chart',
            'echarts_min_series': 2,
            'echarts_no_placeholder_series_name': True,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
            'echarts_xaxis_unique': True,
        },
        {
            'case_id': 'STK-08',
            'name': '橫向 100% stacked bar',
            'query': '各公司申請類別占比分佈,用水平 stacked bar 呈現',
            'type': 'happy_path',
            'expected_chart': 'horizontal 100% stacked bar',
            'expected_q_cols_any': ['company_code', 'application_category'],
            'echarts_data_length_aligned_horizontal': True,
            'echarts_min_series': 2,
            'echarts_no_placeholder_series_name': True,
            'echarts_required_keys': ['title', 'xAxis', 'yAxis', 'series'],
            'echarts_should_have_stack': True,
            'echarts_should_have_xaxis_value': True,
            'echarts_should_have_yaxis_category': True,
        },
    ],
}
