"""
make_ai_code.py — v0.3.3+

從當前 source files 自動生成 `AI_CODE.md`(完整源碼快照,給 LLM agent 用)。

# 用法
```bash
python make_ai_code.py
```

每次發版前跑一次,讓 AI_CODE.md 跟 source 同步。

# 哲學
AI_CODE.md 是「current source 快照」 — 跟 AI_CONTEXT.md(narrative + API)互補。
配合 git tag,某個 release 的 AI_CODE.md 內容就是該 tag 的源碼狀態。

# 不 embed 的東西
- `__pycache__/` / `.venv/` / `.git/`
- `data/*.csv` 原始資料(太大且非程式碼)
- 自動生成的 `test_results.md` / `test_results.json`
- `AI_CONTEXT.md` / `AI_CODE.md` / `CHANGELOG.md`(防自參照)
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
OUTPUT_PATH = PROJECT_ROOT / "AI_CODE.md"


# Top-level files,順序很重要(以邏輯閱讀順序排)
TOP_FILES = [
    # 設定 / 依賴
    "requirements.txt",
    ".env.example",
    "config.py",

    # 核心
    "llm_service.py",
    "app.py",

    # v0.3.x Repository 層
    "prompt_repository.py",
    "test_case_repository.py",
    "test_run_repository.py",

    # Embedded fallback
    "embedded_prompts.py",
    "embedded_metadata.py",
    "embedded_test_cases.py",

    # Domain metadata 範本
    "tflex_task_metadata_agent_v3.py",

    # 測試
    "test_runner.py",
    "test_generality.py",
]

# Migration scripts
MIGRATIONS = [
    "migrations/001_seed_prompts.py",
    "migrations/002_seed_metadata.py",
    "migrations/003_seed_test_cases.py",
]

# Streamlit admin pages
PAGES = [
    "pages/01_test_cases.py",
    "pages/02_test_runs.py",
    "pages/03_prompts.py",
    "pages/04_metadata.py",
]

# Admin CLI tools
ADMIN = [
    "admin/list_prompts.py",
    "admin/list_test_runs.py",
    "admin/mark_baseline.py",
    "admin/compare_baseline.py",
]

# 其他 metadata fixtures(歷史 v0.2.x 跨 domain 測試用,留著參考)
EXTRA = [
    "_test_ecommerce_metadata.py",
    "_test_healthcare_metadata.py",
]


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return f"⚠️ File not found: {path.relative_to(PROJECT_ROOT)}"
    except Exception as e:
        return f"⚠️ Read failed ({e}): {path.relative_to(PROJECT_ROOT)}"


def _detect_language(filename: str) -> str:
    """根據副檔名選 markdown code fence 語言。"""
    if filename.endswith(".py"):
        return "python"
    if filename.endswith(".txt"):
        return "text"
    if filename.endswith(".example") or filename.endswith(".env"):
        return "bash"
    if filename.endswith(".sh"):
        return "bash"
    if filename.endswith(".md"):
        return "markdown"
    if filename.endswith(".json"):
        return "json"
    return ""


def _section(idx: str, rel_path: str, content: str) -> str:
    """產一個 `## idx · path` 區段 + ```lang block。"""
    lang = _detect_language(rel_path)
    fence = f"```{lang}\n" if lang else "```\n"
    return (
        f"## {idx} · `{rel_path}`\n\n"
        f"{fence}{content.rstrip()}\n```\n\n"
    )


def main():
    now = _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")

    # 用 git 拿當前 tag(若有)
    try:
        import subprocess
        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            capture_output=True, text=True, cwd=PROJECT_ROOT, timeout=2,
        )
        git_tag = result.stdout.strip() if result.returncode == 0 else "unknown"
    except Exception:
        git_tag = "unknown"

    # Header
    lines = [
        "# AI_CODE — GenBI 完整源碼快照",
        "",
        f"> Auto-generated by `make_ai_code.py` at `{now}` (git: `{git_tag}`)",
        ">",
        "> 配合 `AI_CONTEXT.md` 使用 — 本檔僅放完整源碼,設計概念 / API / deployment 在 AI_CONTEXT.md。",
        "",
        "# 📌 用途",
        "",
        "- 給 LLM agent / 接手開發者直接看完整實作(不必 navigate repo)",
        "- 等同一個 git tag 的源碼狀態(`make_ai_code.py` 每次發版前 regenerate)",
        "- 跟 `AI_CONTEXT.md` 互補:**架構讀 AI_CONTEXT、實作讀 AI_CODE**",
        "",
        "# 🔄 如何 regenerate",
        "",
        "```bash",
        "python make_ai_code.py",
        "```",
        "",
        "# 🗂 目錄",
        "",
        "## Section A · Top-level files",
    ]

    # 目錄
    for i, fn in enumerate(TOP_FILES, 1):
        lines.append(f"- A.{i} · `{fn}`")
    lines.append("")
    lines.append("## Section B · Migration scripts")
    for i, fn in enumerate(MIGRATIONS, 1):
        lines.append(f"- B.{i} · `{fn}`")
    lines.append("")
    lines.append("## Section C · Streamlit admin pages (`pages/`)")
    for i, fn in enumerate(PAGES, 1):
        lines.append(f"- C.{i} · `{fn}`")
    lines.append("")
    lines.append("## Section D · Admin CLI (`admin/`)")
    for i, fn in enumerate(ADMIN, 1):
        lines.append(f"- D.{i} · `{fn}`")
    lines.append("")
    lines.append("## Section E · v0.2.x 測試 fixtures(歷史保留)")
    for i, fn in enumerate(EXTRA, 1):
        lines.append(f"- E.{i} · `{fn}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # 內容
    lines.append("# 📂 Section A · Top-level files\n")
    for i, fn in enumerate(TOP_FILES, 1):
        lines.append(_section(f"A.{i}", fn, _read(PROJECT_ROOT / fn)))

    lines.append("# 📂 Section B · Migration scripts\n")
    for i, fn in enumerate(MIGRATIONS, 1):
        lines.append(_section(f"B.{i}", fn, _read(PROJECT_ROOT / fn)))

    lines.append("# 📂 Section C · Streamlit admin pages\n")
    for i, fn in enumerate(PAGES, 1):
        lines.append(_section(f"C.{i}", fn, _read(PROJECT_ROOT / fn)))

    lines.append("# 📂 Section D · Admin CLI tools\n")
    for i, fn in enumerate(ADMIN, 1):
        lines.append(_section(f"D.{i}", fn, _read(PROJECT_ROOT / fn)))

    lines.append("# 📂 Section E · 歷史保留(v0.2.x 測試 fixtures)\n")
    for i, fn in enumerate(EXTRA, 1):
        lines.append(_section(f"E.{i}", fn, _read(PROJECT_ROOT / fn)))

    output = "\n".join(lines)
    OUTPUT_PATH.write_text(output, encoding="utf-8")

    size_kb = OUTPUT_PATH.stat().st_size / 1024
    n_files = (
        len(TOP_FILES) + len(MIGRATIONS) + len(PAGES) + len(ADMIN) + len(EXTRA)
    )
    print(f"✅ AI_CODE.md 生成完成")
    print(f"   File:  {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")
    print(f"   Size:  {size_kb:,.1f} KB ({len(output):,} chars)")
    print(f"   Files: {n_files} embedded")
    print(f"   Tag:   {git_tag}")


if __name__ == "__main__":
    main()
